#데이터베이스, 로그레벨, 모니터링, 여러 오픈소스 연결 세팅

server:
  address: localhost
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_schema?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: kali7601**
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false


springdoc:
  swagger-ui:
    path: /api-test
    operations-sorter: method

jwt:
  header: Authorization
  secret: pWqAb8znKpEtkhfQNlyLcH1dKE1TxESS75phjL9kfA
  token-validity-in-seconds: 86400
